
# -------- Общие настройки --------
doc_code_regex: '^[A-ZА-Я0-9]{2,}\.[0-9]{3,}\.[0-9]{3,}[A-ZА-Я0-9-]*$'
name_min_font_size: 18
name_y_window: 60

# -------- Коды -> типы --------
code_suffix_map:
  СБ: "Сборочный чертеж"
  ВО: "Чертеж общего вида"
  ТЧ: "Теоретический чертеж"
  ГЧ: "Габаритный чертеж"
  МЭ: "Электромонтажный чертеж"
  МЧ: "Монтажный чертеж"
  УЧ: "Упаковочный чертеж"
  ВС: "Ведомость спецификаций"
  ВД: "Ведомость ссылочных документов"
  ВП: "Ведомость покупных изделий"
  ВИ: "Ведомость разрешения применения покупных изделий"
  ДП: "Ведомость держателей подлинников"
  ПТ: "Ведомость технического предложения"
  ЭП: "Ведомость эскизного проекта"
  ТП: "Ведомость технического проекта"
  ПЗ: "Пояснительная записка"
  ВДЭ: "Ведомость электронных документов"
  ТУ: "Технические условия"
  ПМ: "Программа и методика испытаний"
  ТБ: "Таблицы"
  РР: "Расчеты"
  РЭ: "Руководство по эксплуатации"
  ИМ: "Инструкция по монтажу, пуску, регулированию и обкатке изделия"
  ФО: "Формуляр"
  ПС: "Паспорт"
  ЭТ: "Этикетка"
  КИ: "Каталог изделия"
  НЗЧ: "Нормы расхода запасных частей"
  НМ: "Нормы расхода материалов"
  ЗИ: "Ведомость ЗИП"
  УП: "Учебно-технические плакаты"
  ИС: "Инструкции эксплуатационные специальные"
  ВЭ: "Ведомость эксплуатационных документов"
  РК: "Руководство по ремонту"
  РС: "Руководство по ремонту"
  УК: "Технические условия на ремонт"
  УС: "Технические условия на ремонт"
  ЗК: "Нормы расхода запасных частей на ремонт"
  ЗС: "Нормы расхода запасных частей на ремонт"
  МК: "Нормы расхода материалов на ремонт"
  МС: "Нормы расхода материалов на ремонт"
  ЗИК: "Ведомость ЗИП на ремонт"
  ЗИС: "Ведомость ЗИП на ремонт"
  ВРК: "Ведомость документов для ремонта"
  ВРС: "Ведомость документов для ремонта"
  Э1: "Схема электрическая структурная"
  Э2: "Схема электрическая функциональная"
  Э3: "Схема электрическая принципиальная"
  Э4: "Схема электрическая соединений"
  Э5: "Схема электрическая подключения"
  Э6: "Схема электрическая общая"
  Э7: "Схема электрическая расположения"
  Г1: "Схема гидравлическая структурная"
  Г3: "Схема гидравлическая принципиальная"
  Г4: "Схема гидравлическая соединения"
  П1: "Схема пневматическая структурная"
  П3: "Схема пневматическая принципиальная"
  П4: "Схема пневматическая соединения"
  Х1: "Схема газовая структурная"
  Х3: "Схема газовая принципиальная"
  Х4: "Схема газовая соединения"
  К1: "Схема кинематическая структурная"
  К2: "Схема кинематическая функциональная"
  К3: "Схема кинематическая принципиальная"
  В1: "Схема вакуумная структурная"
  В3: "Схема вакуумная принципиальная"
  В4: "Схема вакуумная соединений"
  Л3: "Схема оптическая принципиальная"
  Р1: "Схема энергетическая структурная"
  Р2: "Схема энергетическая функциональная"
  Р3: "Схема энергетическая принципиальная"
  Р4: "Схема энергетическая соединений"
  Р5: "Схема энергетическая подключения"
  Р6: "Схема энергетическая общая"
  Р7: "Схема энергетическая расположения"


# -------- Подстановки --------
code_wildcards:
  - prefix: "И"
    name: "Инструкция"
  - prefix: "Д"
    name: "Документы прочие"
